name: Rust

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --manifest-path pewpew/Cargo.toml
    - name: Run tests
      run: cargo test --verbose
