on: push
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sdl2
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev
      - name: Run Clippy
        run: |
          output=$(cargo clippy --all-targets --all-features --manifest-path pewpew/Cargo.toml)
          echo "$output"
