[package]
name = "pewpew"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
env_logger = "0.11.8"
hecs = "0.10.5"
serialport = "4.7.2"

[dependencies.sdl2]
version = "0.38.0"
default-features = false
features = ["image"]